server:
  port: 8080

spring:
  profiles:
    active: local # local profile 사용하기 위한 설정
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:~/flyway;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  flyway:
    enabled: false # 기본값 = true 이지만, flyway를 사용하고 있음을 명시해줍니다.
    baseline-on-migrate: true

